### ISSUE TITLE
Other display resolution

### ISSUE THREAD

**Issue by desevensa** [michal037/driver-ST7735S#3]
Hi, Im using your driver to setup a different display with the same chipset (ST7735S) 
![imagen](https://user-images.githubusercontent.com/37191197/78709435-44755d00-78d9-11ea-9171-e29b9db352bd.png)

I followed the instructions and I get almost expected control on the screen but not really flawless like coordinates (0,0) for an square are like 5 pixels at left than really is it. I recorded a video of it, I hope it explains better than me (https://www.dailymotion.com/video/x7t5vh1).

I am using a raspberry 3b and the display in the picture (0.96 inch, 80x160)

My goals are
1. Set it up as a microDesktop screen but i have not luck yet (still looking for find it out)
2. Set it up on an OrangePi zero too, but i get random colored pixels. 

I hope you can help me if I am doing something wrong. 

Thx.

**Comment by michal037** [comment]
Hi,
I apologize for the response time.
I will try to help you as soon as possible.  First, I prepare Raspberry for me and I will make a short video for you.

**Comment by michal037** [comment]
On this address (https://www.youtube.com/watch?v=HY1hHUi0-1o) you can see how it looks like for me.

---

![image1](https://user-images.githubusercontent.com/7441419/79033872-141c1000-7bb2-11ea-8d47-255ff9d791e1.png)

Look at the notes in the picture.
I marked the line numbers from main.c, where is the top and where is the first and last pixel on my display.
Note that the main function has constant coordinates for squares and lines. They are not prepared for your resolution, that's why lines are cropped at end. So don't worry about the lines and pay attention to the squares. They are at the very beginning.

Think of the display as a window of part of the driver's RAM.

Your pixel (0, 0) that is in the beginning of your window is in a different position in the RAM memory than (0, 0) address.

To fix this, you need to move the window accordingly. To such addresses from the RAM of your driver, on which what you draw will show on the display.

This is `offset`, which is relative to a (0, 0) point in RAM memory. The offset for width and height may be different.

Try this:

[in this place](https://github.com/michal037/driver-ST7735S/blob/50946c7fcdb9fa4223743987852903df4b5a85e4/source/st7735s.h#L32):
```c
/* The data type for one display */
typedef struct
{
	int cs, a0, rs;
	uint8 width, height;
	uint8 offset_width, offset_height;
} lcdst_t;
```

[in this place](https://github.com/michal037/driver-ST7735S/blob/50946c7fcdb9fa4223743987852903df4b5a85e4/source/st7735s.c#L192) (Note that I changed the resolution to yours.):
```c
void lcdst_setOrientation(uint8 orientation)
{
	writeCommand(0x36); /* Memory Data Access Control */

	switch(orientation)
	{
		case 1:
			writeData(0x60); /* MX + MV */
			activeDisplay->width  = 160;
			activeDisplay->height = 80;
			activeDisplay->offset_width  = YOUR_VALUE_WRITE_HERE;
			activeDisplay->offset_height = YOUR_VALUE_WRITE_HERE;
			lcdst_setWindow(0, 0, 159, 79);
			break;

		case 2:
			writeData(0xC0); /* MY + MX */
			activeDisplay->width  = 80;
			activeDisplay->height = 160;
			activeDisplay->offset_width  = YOUR_VALUE_WRITE_HERE;
			activeDisplay->offset_height = YOUR_VALUE_WRITE_HERE;
			lcdst_setWindow(0, 0, 79, 159);
			break;

		case 3:
			writeData(0xA0); /* MY + MV */
			activeDisplay->width  = 160;
			activeDisplay->height = 80;
			activeDisplay->offset_width  = YOUR_VALUE_WRITE_HERE;
			activeDisplay->offset_height = YOUR_VALUE_WRITE_HERE;
			lcdst_setWindow(0, 0, 159, 79);
			break;

		default:
			writeData(0x00); /* None */
			activeDisplay->width  = 80;
			activeDisplay->height = 160;
			activeDisplay->offset_width  = YOUR_VALUE_WRITE_HERE;
			activeDisplay->offset_height = YOUR_VALUE_WRITE_HERE;
			lcdst_setWindow(0, 0, 79, 159);
			break;
	}
} /* lcdst_setOrientation */
```

[in this place](https://github.com/michal037/driver-ST7735S/blob/50946c7fcdb9fa4223743987852903df4b5a85e4/source/st7735s.c#L250):
```c
uint8 lcdst_setWindow(uint8 x1, uint8 y1, uint8 x2, uint8 y2)
{
	/* Accept: 0 <= x1 <= x2 < activeDisplay->width */
	if(x2 < x1) return 1;
	if(x2 >= activeDisplay->width) return 1;
	
	/* Accept: 0 <= y1 <= y2 < activeDisplay->height */
	if(y2 < y1) return 1;
	if(y2 >= activeDisplay->height) return 1;
	
	/* Set column address */
	writeCommand(0x2A);
	writeData(0); writeData(x1 + activeDisplay->offset_width);
	writeData(0); writeData(x2 + activeDisplay->offset_width);
	
	/* Set row address */
	writeCommand(0x2B);
	writeData(0); writeData(y1 + activeDisplay->offset_height);
	writeData(0); writeData(y2 + activeDisplay->offset_height);
	
	/* Activate RAW write */
	writeCommand(0x2C);
	
	return 0;
} /* lcdst_setWindow */
```

Here you must increase the offset until pixel (0, 0) appears on your display in the correct place.
There may be a problem when you start changing `lcdst_setOrientation()`. Because the offset will have to be adjusted to the orientation.


Try this code in main.c for test. Also check the height, because the pixel may not appear.
```c
lcdst_setOrientation(0);
lcdst_drawScreen(0, 0, 0);
lcdst_drawPx(0, 0, 255, 255, 255);
```

---

I know this code is not perfect. The problem is that I don't have all the modules so that I can extend the code and run tests on them.

---

Have you changed the colors in main.c? I ask because they look different. If not, you may have other endianness or different number of colors does it.

I checked the specification of your module on the Internet. It looks like it has 65K different colors. Where this driver is prepared and tested for 262K and 4K colors.

262K mode should work OK, but you'll have big steps to change for another color. It would be necessary to analyze the documentation and correct bit operations for 65K mode. 4K mode should work correctly for you.

---

Feel free to write with any problem. I could have forgotten something in all this.

**Comment by desevensa** [comment]
Hi, I made the changes and fixed the values of your answer and it fixed perfectly, also I modified to show four black lines as a frame from 1px from the border and there is no noisy lines. 
![IMG_20200411_114421](https://user-images.githubusercontent.com/37191197/79049818-5d3c8600-7beb-11ea-8220-6bac18f007cf.jpg)
(Ignore the tainted lines, it is from my camera)

About the colors I keep the original values of your code, it looks like it's casually working on YMC standard instead RGB. I guess an small hack coding of transformation between those standards could fix that issue.

About OrangePi, I will search about it, this is the first time I do something with SPI and my knowledge about it is still very limited. I will tell you about any important information I can get.

Thank you for your help, it was very usefull.

**Comment by desevensa** [comment]
Hi, I've been working on Raspberry about colors and I realized the colors are not on YMC standard, there are working with cross red-blue channels and values are negative.

Well, if I want a value for rgb (100, 50, 255) I have to code it as follows
( 255-b, 255-g, 255-r) = (255-100, 255-50, 255-255) = (155, 205, 0).

As I said before, a bit of code for fix that is not really complex and I suppose the right place for it is on _st7735s.h_ (I have to use my free time for it), but now...  how can I get a microDesktop display for Xwindows?

I have tried commands found on many pages but still doesnt work, no matters if colors are wrong for now. Any idea?

**Comment by michal037** [comment]
Your idea with this frame is great.

---

I used these specific colors because I liked them, nothing more. I must change them. Everything is in RGB standard.

---

63 page from the documentation v1.4 for 3-line SPI (without using MISO) (565 color mode):

![565](https://user-images.githubusercontent.com/7441419/79412698-668c7080-7fa6-11ea-90f8-fc728067cac0.png)


To display one pixel you have to send two bytes. So you have to prepare these two bytes in one 'packet'. You have 5 bits for red. 6 bits for green. 5 bits for blue. Where green is partly in both bytes. If you prepare them, then you have to send first byte, then second byte. In this order. Then the cycle repeats for the next pixel. You don't need to subtract anything here, generally. I don't remember exactly anymore, but I didn't use these 'const 1 bit' and it worked. Probably with bug :/. I need to check it in my free time and improve it.
Unless I misunderstood and each of us thinks about something different.

---

Maybe try to use https://github.com/adafruit/Adafruit-ST7735-Library ? This library is more universal.

---

> but now... how can I get a microDesktop display for Xwindows?

I have never used it. I really don't know. I always connect via SSH or HDMI cable.

**Comment by desevensa** [comment]
Hi, thanks for your advice. I thought ST7731 and ST7731S was really different but those worked at first on Orange PI. I have the same issues (swaping of red and blue channels and one pixels line of random values at edge of screen) but I can deal with it.

Also I can get startX for desktop easily.

I'm not sure if that ends this topic but I suppose I will keep using that driver.

Thank you, again, very much for your help.
